import { MetadataRoute } from 'next';

export default function manifest(): MetadataRoute.Manifest {
    return {
        name: 'Professional Document Automation System',
        short_name: 'Professional Document Automation System',
        description: 'Official Armenian documents generated by AI, delivered as PDF',
        icons: [],
        screenshots: [],
        id: '/',
        start_url: '/',
        background_color: '#FFFFFF',
        display: 'standalone',
        scope: '/',
        orientation: 'portrait',
        theme_color: '#000000',
    };
}
